### ISSUE TITLE
submit should automatically concat commit messages

### ISSUE THREAD

**Issue by anantdamle** [GoogleCloudPlatform/git-gerrit-subcommand#6]
`git gerrit submit` should concat all messages from commits it is squashing for gerrit submission.
Currently the commit message only comes populated with Change-Id, requiring the user to type in commit messages all over again.

**Comment by anantdamle** [comment]
e.g.
```
Type Your Title | [preivous title]
<empty line>
[
 concat of previous commit messages
]
<empty line>
Change-Id:dgfdgdfgdf
```

**Comment by ChaosEternal** [comment]
The new behavior becomes:
when submit the first time after a gerrit start-work, this tool will guess for your submission commit message from the history;
following submission will re-use the submission message of the first submission.
